import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import {fileURLToPath} from 'node:url';
import {FunctionTool, LlmAgent, LLMRegistry, requestInputTool} from '@google/adk';
import {z} from 'zod';
import {BedrockLlm} from './bedrock_llm.js';
import {LocalSkillToolset} from './skill_toolset.js';

// Register the Bedrock connector so any `bedrock/...` model string resolves to
// it. (Same registration `agent.ts` does — harmless to call more than once.)
LLMRegistry.register(BedrockLlm);

const PROJECT_ROOT = path.dirname(fileURLToPath(import.meta.url));

// The locked spec is persisted here. There is ONE comprehensive spec per run:
// a single JSON (machine-readable) and a single Markdown (human-readable), both
// covering every feature the user asked for. Stable filenames — a new run
// overwrites them with the current, complete spec. Generated at runtime,
// gitignored, not checked in.
const FEATURE_SPECS_DIR = path.join(PROJECT_ROOT, 'feature-specs');
const PROJECT_SPEC_JSON_PATH = path.join(FEATURE_SPECS_DIR, 'project-spec.json');
const PROJECT_SPEC_MD_PATH = path.join(FEATURE_SPECS_DIR, 'project-spec.md');

/** Undo the HTML entity escaping a model sometimes applies to `<`, `>`, `&`. */
function unescapeHtml(text: string): string {
  return text
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#0?39;/g, "'")
    .replace(/&amp;/g, '&');
}

/** Renders one feature (within the comprehensive spec) as a Markdown section. */
function renderFeatureMarkdown(feature: Record<string, any>, index: number): string {
  const clean = (s: unknown) => unescapeHtml(String(s ?? ''));
  const bullets = (items: unknown): string =>
    Array.isArray(items) && items.length
      ? items.map((i) => `- ${clean(i)}`).join('\n')
      : '_None._';

  const priority = feature.priority
    ? ` _(priority: ${clean(feature.priority)})_`
    : '';
  const lines: string[] = [
    `## ${index}. ${clean(feature.title)}${priority}`,
    '',
    `**Summary** — ${clean(feature.summary)}`,
    '',
    `**Motivation** — ${clean(feature.motivation)}`,
    '',
    '**Requirements**',
    bullets(feature.requirements),
    '',
    '**Acceptance criteria**',
    bullets(feature.acceptance_criteria),
    '',
    '**Decisions made**',
    Array.isArray(feature.decisions) && feature.decisions.length
      ? feature.decisions
          .map((d: any) => `- ${clean(d.question)} → ${clean(d.answer)}`)
          .join('\n')
      : '_None._',
    '',
    '**Out of scope**',
    bullets(feature.out_of_scope),
  ];
  if (Array.isArray(feature.open_questions) && feature.open_questions.length) {
    lines.push('', '**Open questions**', bullets(feature.open_questions));
  }
  return lines.join('\n');
}

/** Renders the whole comprehensive spec (overview + every feature) as Markdown. */
export function renderProjectSpecMarkdown(spec: Record<string, any>): string {
  const clean = (s: unknown) => unescapeHtml(String(s ?? ''));
  const features: Array<Record<string, any>> = Array.isArray(spec.features)
    ? spec.features
    : [];

  const header = [
    `# ${clean(spec.project) || 'Planner'} — Feature Spec`,
    '',
    `_${spec.status ?? 'locked'} · ${clean(spec.created_at)} · ${features.length} feature${features.length === 1 ? '' : 's'}._`,
    '',
    '> Generated by the planner intake agent. One comprehensive spec covering all agreed features.',
  ];
  if (spec.overview) {
    header.push('', '## Overview', '', clean(spec.overview));
  }
  if (features.length) {
    const contents = features
      .map((f, i) => `${i + 1}. ${clean(f.title)}`)
      .join('\n');
    header.push('', '## Features', '', contents);
  }
  if (spec.notes) {
    header.push('', `**Notes** — ${clean(spec.notes)}`);
  }

  const body = features
    .map((f, i) => renderFeatureMarkdown(f, i + 1))
    .join('\n\n---\n\n');

  return features.length
    ? `${header.join('\n')}\n\n---\n\n${body}\n`
    : `${header.join('\n')}\n`;
}

/**
 * Persists the ONE comprehensive, *locked* spec for the planner project — a
 * single document covering every feature the user asked for. This is the final
 * step of the `feature-intake` playbook: it is only called once the blocking
 * open questions for ALL features have been resolved with the user (via
 * `adk_request_input`), so the artifact represents agreed decisions, not guesses.
 *
 * The tool does no "understanding" of its own — the model fills in the
 * structured fields from the conversation. Its job is to turn the agreed set of
 * features into one real, inspectable JSON + Markdown pair on disk.
 */
const featureSchema = z.object({
  title: z
    .string()
    .describe('Short feature name, e.g. "Recurring tasks" or "Bookmark editing".'),
  summary: z
    .string()
    .describe('One-paragraph plain-language description of the feature as agreed.'),
  motivation: z
    .string()
    .describe(
      'Who this is for and why they need it — the problem it solves. ' +
        'User-facing value, not implementation.',
    ),
  requirements: z
    .array(z.string())
    .describe(
      'The concrete, locked-in functional requirements. Each item is a single ' +
        'unambiguous statement of something the feature must do.',
    ),
  acceptance_criteria: z
    .array(z.string())
    .describe(
      'Testable statements that must all be true for the feature to be done. ' +
        'Phrase each so it is objectively checkable.',
    ),
  decisions: z
    .array(
      z.object({
        question: z.string().describe('The clarifying question you asked the user.'),
        answer: z
          .string()
          .describe("The user's answer that resolved it (or the agreed default)."),
      }),
    )
    .describe(
      'The audit trail of every ambiguity you surfaced for THIS feature and ' +
        'how it was settled. This is what makes it a locked decision.',
    ),
  out_of_scope: z
    .array(z.string())
    .optional()
    .describe('Things explicitly agreed to be NOT part of this feature.'),
  open_questions: z
    .array(z.string())
    .optional()
    .describe(
      'Any non-blocking questions left for later. Blocking ones should have ' +
        'been asked before locking, so this is normally empty.',
    ),
  priority: z
    .enum(['low', 'medium', 'high'])
    .optional()
    .describe('Relative priority for the planner backlog, if the user gave one.'),
});

const createProjectSpec = new FunctionTool({
  name: 'create_project_spec',
  description:
    'Persists the ONE comprehensive LOCKED specification for the planner ' +
    'project — a single document covering EVERY feature the user asked for — as ' +
    'both `feature-specs/project-spec.json` and a human-readable ' +
    '`feature-specs/project-spec.md`. Call this EXACTLY ONCE per run, at the ' +
    'end, with ALL features in the `features` array — never one call per ' +
    'feature. Call it only AFTER you have resolved the blocking open questions ' +
    'for every feature with the user (via `adk_request_input`); it records ' +
    'agreed decisions, not guesses. Returns the spec and both file paths.',
  parameters: z.object({
    project: z
      .string()
      .describe('The project name, e.g. "personal-planner".')
      .default('personal-planner'),
    overview: z
      .string()
      .describe(
        'A short integrated overview of the whole set of features: the common ' +
          'context and how they fit together. This is what makes the output one ' +
          'coherent spec rather than a pile of unrelated items.',
      ),
    features: z
      .array(featureSchema)
      .min(1)
      .describe(
        'EVERY feature to include in this comprehensive spec, each fully ' +
          'specified. Include all of them in this one call.',
      ),
    notes: z.string().optional().describe('Any cross-cutting context worth carrying forward.'),
  }),
  execute: async (args) => {
    const spec = {
      spec_id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      created_at: new Date().toISOString(),
      status: 'locked' as const,
      ...args,
    };
    await fs.mkdir(FEATURE_SPECS_DIR, {recursive: true});
    await fs.writeFile(PROJECT_SPEC_JSON_PATH, JSON.stringify(spec, null, 2), 'utf-8');
    await fs.writeFile(PROJECT_SPEC_MD_PATH, renderProjectSpecMarkdown(spec), 'utf-8');
    return {
      status: 'success',
      spec_id: spec.spec_id,
      feature_count: spec.features.length,
      json_path: PROJECT_SPEC_JSON_PATH,
      markdown_path: PROJECT_SPEC_MD_PATH,
    };
  },
});

/**
 * Reads a local requirements / feature-request file (e.g. a Markdown doc) so
 * the user can hand the agent a file instead of pasting its contents. Returns
 * the raw text for the model to treat as the intake source. Deliberately
 * read-only and text-only — it never writes, and refuses binary or oversized
 * files rather than dumping garbage into the conversation.
 */
const MAX_FILE_BYTES = 256 * 1024;

const readRequirementsFile = new FunctionTool({
  name: 'read_requirements_file',
  description:
    'Reads a local text/Markdown file (a requirements doc or feature request) ' +
    'and returns its contents, so the user can point you at a file instead of ' +
    'pasting it. Use this first when the user gives a file path, then run the ' +
    '`feature-intake` playbook over what it contains. Read-only.',
  parameters: z.object({
    path: z
      .string()
      .describe(
        'Path to the file to read. Absolute, or relative to where the agent ' +
          'was started.',
      ),
  }),
  execute: async ({path: filePath}) => {
    const resolved = path.resolve(filePath);
    let stat;
    try {
      stat = await fs.stat(resolved);
    } catch {
      return {status: 'error', error_message: `No file found at '${resolved}'.`};
    }
    if (!stat.isFile()) {
      return {status: 'error', error_message: `'${resolved}' is not a file.`};
    }
    if (stat.size > MAX_FILE_BYTES) {
      return {
        status: 'error',
        error_message: `File is ${stat.size} bytes; refusing to read more than ${MAX_FILE_BYTES}. Trim it or paste the relevant part.`,
      };
    }
    const buffer = await fs.readFile(resolved);
    // Reject files with NUL bytes — a cheap "this is binary, not text" check.
    if (buffer.includes(0)) {
      return {
        status: 'error',
        error_message: `'${resolved}' looks like a binary file, not text.`,
      };
    }
    return {status: 'success', path: resolved, content: buffer.toString('utf-8')};
  },
});

// The intake playbook (surface ambiguities → ask → lock) lives in a skill so it
// can be edited without touching this file, and so the "ask before locking"
// discipline is a documented, inspectable artifact. A dedicated skills dir keeps
// this agent focused on just the intake skill (the shared `skills/` dir carries
// the city_assistant's unrelated skills).
const skillToolset = new LocalSkillToolset(path.join(PROJECT_ROOT, 'planner_skills'));

export const rootAgent = new LlmAgent({
  name: 'planner_feature_intake',
  model: process.env.BEDROCK_MODEL ?? 'bedrock/us.anthropic.claude-sonnet-4-6',
  description:
    'Gathers feature requirements for the planner project from a user, asks ' +
    'clarifying questions to resolve ambiguity, and only then locks the ' +
    'decision into a persisted feature spec.',
  instruction: [
    'You are a requirements analyst for the user\'s "planner" project. Your job',
    'is to turn rough feature requests into ONE clear, agreed, comprehensive',
    'locked spec that comprises ALL the features — never to start building them.',
    '',
    'If the user gives you a file path (e.g. a requirements doc) instead of',
    'typing the request, call `read_requirements_file` on that path first and',
    'treat its contents as the source. A doc may describe several features or',
    'gaps — gather ALL of them and cover them in the single comprehensive spec.',
    '',
    'Follow the `feature-intake` skill: it is the playbook for how to surface',
    'ambiguities, ask about them, and lock one comprehensive spec. Load it',
    'before you begin.',
    '',
    'The single most important rule: DO NOT lock a decision (do not call',
    '`create_feature_spec`) while a genuine ambiguity that would change the',
    'scope, behaviour, or acceptance of the feature is still unresolved. When',
    'you hit such an ambiguity, call `adk_request_input` to ask the user a',
    'focused question and WAIT for their answer — do not guess, and do not',
    'silently pick one interpretation.',
    '',
    'Be economical with questions. Only ask about things that genuinely change',
    'the outcome. For minor choices where a sensible default exists, state the',
    'default you are assuming (and record it in that feature\'s `decisions`)',
    'rather than interrupting the user. Prefer batching related questions into',
    'one `adk_request_input` call over a long back-and-forth.',
    '',
    'Call `create_project_spec` EXACTLY ONCE, at the very end, with EVERY',
    'feature in its `features` array and a short integrated `overview` — never',
    'once per feature. Then report the result to the user in the format the',
    'skill describes.',
  ].join('\n'),
  tools: [readRequirementsFile, createProjectSpec, requestInputTool, skillToolset],
});
